server:
  port: 8024
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: jangka512@gmail.com
    password: sadppakfrnqfbjar
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/insta?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.sbs.untactTeacher.dto
custom:
  genFileDirPath: C:/work/insta-usr-sb-file
  needToChangePasswordFreeDays: 50
  siteMainUri: http://localhost:8024/
  siteName: 인스타
  emailFrom: no-reply@localhost
  emailFromName: 인스타알림봇
  logging:
    dir: log
    level: debug